[tool.poetry]
name = "homebot"
version = "2.1.0"
description = "A Telegram bot written in Python"
authors = ["Sebastiano Barezzi <barezzisebastiano@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
cowsay = "^3.0"
GitPython = "^3.1.13"
paramiko = "^2.7.2"
PyGithub = "^1.54.1"
python-telegram-bot = "^13.2"
python-dotenv = "^0.15.0"
requests = "^2.25.1"
speedtest-cli = "^2.1.2"
twrpdtgen = "^1.2.4"
natsort = "^7.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
